# Generated by Django 5.2.8 on 2025-12-03 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_emocion', models.CharField(max_length=50)),
                ('persepcion_emocion', models.IntegerField()),
                ('categoria', models.CharField(choices=[('basica', 'Básica'), ('secundaria', 'Secundaria'), ('otra', 'Otra')], default='basica', max_length=20)),
            ],
            options={
                'db_table': 'Emocion',
            },
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_habilidad', models.CharField(max_length=150)),
                ('modulo', models.CharField(choices=[('mindfulness', 'Mindfulness'), ('tolerancia_malestar', 'Tolerancia al Malestar'), ('regulacion_emocional', 'Regulación Emocional'), ('efectividad_interpersonal', 'Efectividad Interpersonal')], max_length=40)),
                ('descripcion_habilidad', models.TextField(blank=True, null=True)),
                ('rango_malestar_min', models.IntegerField()),
                ('rango_malestar_max', models.IntegerField()),
                ('imagen_url', models.CharField(blank=True, max_length=255, null=True)),
                ('habilidad_activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Habilidad',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('email_usuario', models.CharField(max_length=255, unique=True)),
                ('nombre_usuario', models.CharField(max_length=150)),
                ('apellido_usuario', models.CharField(max_length=150)),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_usuario', models.CharField(blank=True, max_length=30, null=True)),
                ('rol', models.CharField(default='usuario', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('usuario_activo', models.BooleanField(default=True)),
                ('metodo_biometrico', models.CharField(choices=[('ninguno', 'Ninguno'), ('huella', 'Huella'), ('cara', 'Reconocimiento facial')], default='ninguno', max_length=20)),
                ('contrasena', models.CharField(max_length=255)),
                ('salt', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion_ejercicio', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('lectura', 'Lectura'), ('audio', 'Audio'), ('visual', 'Visual'), ('escrito', 'Escrito')], default='lectura', max_length=20)),
                ('duracion_aprox_min', models.IntegerField(blank=True, null=True)),
                ('imagen_url', models.CharField(blank=True, max_length=255, null=True)),
                ('audio_url', models.CharField(blank=True, max_length=255, null=True)),
                ('material_extra', models.JSONField(blank=True, null=True)),
                ('ejercicio_activo', models.BooleanField(default=True)),
                ('id_habilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hk.habilidad')),
            ],
            options={
                'db_table': 'Ejercicio',
            },
        ),
        migrations.CreateModel(
            name='RegistroEmocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('pensamientos', models.TextField(blank=True, null=True)),
                ('sensaciones', models.TextField(blank=True, null=True)),
                ('contexto', models.TextField(blank=True, null=True)),
                ('registro_sincronizado', models.BooleanField(default=False)),
                ('id_emocion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hk.emocion')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hk.usuario')),
            ],
            options={
                'db_table': 'RegistroEmocional',
            },
        ),
        migrations.CreateModel(
            name='RegistroCrisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('nivel_inicial', models.IntegerField()),
                ('nivel_final', models.IntegerField(blank=True, null=True)),
                ('duracion_crisis_segundos', models.IntegerField(blank=True, null=True)),
                ('contacto_emergencia_usado', models.BooleanField(default=False)),
                ('crisis_sincronizado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hk.usuario')),
            ],
            options={
                'db_table': 'RegistroCrisis',
            },
        ),
        migrations.CreateModel(
            name='PracticaHabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_practica', models.DateTimeField(auto_now_add=True)),
                ('duracion_practica_segundos', models.IntegerField(blank=True, null=True)),
                ('nota_usuario', models.TextField(blank=True, null=True)),
                ('sincronizado', models.BooleanField(default=False)),
                ('id_ejercicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hk.ejercicio')),
                ('id_habilidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hk.habilidad')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hk.usuario')),
            ],
            options={
                'db_table': 'PracticaHabilidad',
            },
        ),
        migrations.CreateModel(
            name='ContactoEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contacto', models.CharField(max_length=150)),
                ('relacion', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_contacto', models.CharField(max_length=30)),
                ('email_contacto', models.CharField(blank=True, max_length=255, null=True)),
                ('orden', models.IntegerField(default=1)),
                ('contacto_activo', models.BooleanField(default=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hk.usuario')),
            ],
            options={
                'db_table': 'ContactoEmergencia',
            },
        ),
        migrations.CreateModel(
            name='CrisisHabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ayudo', models.BooleanField(null=True)),
                ('orden_uso', models.IntegerField(null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('id_habilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hk.habilidad')),
                ('id_crisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hk.registrocrisis')),
            ],
            options={
                'db_table': 'Crisis_Habilidad',
                'unique_together': {('id_crisis', 'id_habilidad')},
            },
        ),
    ]
