# Generated by Django 5.2.8 on 2025-12-09 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactoemergencia',
            old_name='relacion',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='contactoemergencia',
            name='contacto_activo',
        ),
        migrations.RemoveField(
            model_name='contactoemergencia',
            name='email_contacto',
        ),
        migrations.RemoveField(
            model_name='contactoemergencia',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='contactoemergencia',
            name='nombre_contacto',
        ),
        migrations.RemoveField(
            model_name='contactoemergencia',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='contactoemergencia',
            name='telefono_contacto',
        ),
        migrations.AddField(
            model_name='contactoemergencia',
            name='numero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactoemergencia',
            name='prioridad',
            field=models.CharField(blank=True, choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contactoemergencia',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='hk.usuario'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='contactoemergencia',
            table=None,
        ),
    ]
