# Generated by Django 5.2.8 on 2025-12-10 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hk', '0002_rename_relacion_contactoemergencia_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercicio',
            name='id_habilidad',
        ),
        migrations.RemoveField(
            model_name='practicahabilidad',
            name='id_ejercicio',
        ),
        migrations.RemoveField(
            model_name='registroemocional',
            name='id_emocion',
        ),
        migrations.RemoveField(
            model_name='practicahabilidad',
            name='id_habilidad',
        ),
        migrations.RemoveField(
            model_name='practicahabilidad',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='registroemocional',
            name='id_usuario',
        ),
        migrations.AlterField(
            model_name='contactoemergencia',
            name='prioridad',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=20),
        ),
        migrations.CreateModel(
            name='HistorialCrisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nivel', models.IntegerField()),
                ('habilidades_usadas', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hk.usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='CrisisHabilidad',
        ),
        migrations.DeleteModel(
            name='Ejercicio',
        ),
        migrations.DeleteModel(
            name='Emocion',
        ),
        migrations.DeleteModel(
            name='Habilidad',
        ),
        migrations.DeleteModel(
            name='PracticaHabilidad',
        ),
        migrations.DeleteModel(
            name='RegistroEmocional',
        ),
    ]
